<?php
/*********************************
List Images page displays all the current 
images from the database WITHOUT any
text

After the user selects an image
then the page should send the user
to the create-meme.php page

image_id is to be sent through 
$_GET or $_SESSION
*********************************/
session_start();


?><!doctype html>
<html>
<head>
	<meta charset="UTF-8">
	<title>Meme List - Meme Generator</title>
	<?php
	include_once( "includes/scripts.inc.php");
	?>
</head>

<body>
	<div class="wrapper">
		<header class="masthead">
			<?php
			include_once("includes/masthead.inc.php");
			?>
		</header>
		
		<nav class="nav" role="navigation">
			<?php
			include_once("includes/nav.inc.php");
			?>	
		</nav>
		
		<section class="main">
			<h2>Choose an Image to Make a Meme</h2>
			<?php
			//the list below to be generated by PHP
			//by selecting the list of images from the database
			?>
			<ul class="memes">
				<li>
					<a href="add-text.php"><img src="images-memes/missing.png" alt="meme image" /><br/>Add Text to this image</a>
				</li>
				<li>
					<a href="add-text.php"><img src="images-memes/missing.png" alt="meme image" /><br/>Add Text to this image</a>
				</li>
				<li>
					<a href="add-text.php"><img src="images-memes/missing.png" alt="meme image" /><br/>Add Text to this image</a>
				</li>
				<li>
					<a href="add-text.php"><img src="images-memes/missing.png" alt="meme image" /><br/>Add Text to this image</a>
				</li>
				<li>
					<a href="add-text.php"><img src="images-memes/missing.png" alt="meme image" /><br/>Add Text to this image</a>
				</li>
				<li>
					<a href="add-text.php"><img src="images-memes/missing.png" alt="meme image" /><br/>Add Text to this image</a>
				</li>
				<li>
					<a href="add-text.php"><img src="images-memes/missing.png" alt="meme image" /><br/>Add Text to this image</a>
				</li>
				<li>
					<a href="add-text.php"><img src="images-memes/missing.png" alt="meme image" /><br/>Add Text to this image</a>
				</li>
				<li>
					<a href="add-text.php"><img src="images-memes/missing.png" alt="meme image" /><br/>Add Text to this image</a>
				</li>
				<li>
					<a href="add-text.php"><img src="images-memes/missing.png" alt="meme image" /><br/>Add Text to this image</a>
				</li>
				<li>
					<a href="add-text.php"><img src="images-memes/missing.png" alt="meme image" /><br/>Add Text to this image</a>
				</li>
				<li>
					<a href="add-text.php"><img src="images-memes/missing.png" alt="meme image" /><br/>Add Text to this image</a>
				</li>
			</ul>
				
		</section>
		
		<footer class="footer">
			<?php
			include_once("includes/footer.inc.php");
			?>
		</footer>
	</div>
</body>
</html>